# Generated by Django 4.2 on 2023-04-12 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bcaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(help_text='Enter a BCAA name', max_length=200)),
                ('brand', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Creatine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(help_text='Enter a creatine name', max_length=200)),
                ('brand', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(help_text='Enter a pre-workout name', max_length=200)),
                ('brand', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(help_text='Enter a protein name', max_length=200)),
                ('brand', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProteinInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('w', 'Wait list'), ('a', 'Available'), ('s', 'Sold Out')], default='o', help_text='Protein availability', max_length=1)),
                ('Protein', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.protein')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreWorkoutInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('w', 'Wait list'), ('a', 'Available'), ('s', 'Sold Out')], default='o', help_text='Preworkout availability', max_length=1)),
                ('PreWorkout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.preworkout')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreatineInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('w', 'Wait list'), ('a', 'Available'), ('s', 'Sold Out')], default='o', help_text='Protein availability', max_length=1)),
                ('Creatine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.creatine')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BcaaInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('w', 'Wait list'), ('a', 'Available'), ('s', 'Sold Out')], default='o', help_text='Bcaa availability', max_length=1)),
                ('Bcaa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.bcaa')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
