# Generated by Django 4.2 on 2023-04-14 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_cart_alter_product_name_cartitem_cart_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
